// <auto-generated />
using System;
using CongNgheStore.Models.DbContext_Folder;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CongNgheStore.Migrations
{
    [DbContext(typeof(CongNgheStoreDBContext))]
    partial class CongNgheStoreDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CongNgheStore.Models.BatteryAndCharger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BatteryCapacity")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BatteryTechnology")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("BatteryType")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MaximumChargingSupport")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("[ProductId] IS NOT NULL");

                    b.ToTable("BatteryAndChargers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BatteryCapacity = "4323 mAh",
                            BatteryTechnology = "Sạc không dây MagSafe,Sạc pin nhanh,Sạc không dây,Tiết kiệm pin",
                            BatteryType = "Li-Ion",
                            MaximumChargingSupport = "20 W",
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46"
                        },
                        new
                        {
                            Id = 2,
                            BatteryCapacity = "3200 mAh",
                            BatteryTechnology = "Sạc không dây,Tiết kiệm pin,Sạc pin nhanh,Sạc không dây MagSafe",
                            BatteryType = "Lithium‑ion",
                            MaximumChargingSupport = "Sạc không dây MagSafe lên đến 15W,Sạc không dây Qi lên đến 7,5W",
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8"
                        },
                        new
                        {
                            Id = 3,
                            BatteryType = "Lithium‑ion",
                            MaximumChargingSupport = "Sạc không dây MagSafe lên đến 15W,Sạc không dây Qi lên đến 7,5W",
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2"
                        },
                        new
                        {
                            Id = 4,
                            BatteryCapacity = "5000 mAh",
                            BatteryTechnology = "Sạc pin nhanh",
                            BatteryType = "Li-Po",
                            MaximumChargingSupport = "25 W",
                            ProductId = "0ed9c3f3-3eac-4717-83ae-7cb866cfaec9"
                        },
                        new
                        {
                            Id = 5,
                            BatteryCapacity = "5000 mAh",
                            MaximumChargingSupport = "25 W",
                            ProductId = "3e8d0cb5-4cf7-4ca9-8c76-88b78fde774a"
                        },
                        new
                        {
                            Id = 6,
                            BatteryCapacity = "5000 mAh",
                            BatteryTechnology = "Siêu tiết kiệm pin",
                            BatteryType = "Li-Po",
                            MaximumChargingSupport = "10 W",
                            ProductId = "e6cd1bce-c1ef-4ccb-a1d0-a122372b3423"
                        },
                        new
                        {
                            Id = 7,
                            BatteryCapacity = "5000 mAh",
                            ProductId = "3c183845-7b58-43bc-8253-036a5ecabff1"
                        },
                        new
                        {
                            Id = 8,
                            BatteryCapacity = "iOS 16",
                            BatteryType = "Li-Po",
                            ProductId = "4d0c8c2d-65a3-47c0-a9e3-8d03eb96f3ca"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(1500)");

                    b.Property<bool>("IsRemove")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Thương hiệu Apple được thành lập từ những năm 1976 tại Hoa Kỳ, cũng là nơi đặt trụ sở chính của công ty đến thời điểm hiện tại. Trải qua nhiều năm, với sự phát triển và thay đổi để hoàn thiện, người dùng trên toàn thế giới bắt đầu biết đến và nhớ tới thương hiệu qua logo quả táo khuyết. Không chỉ thế, người dùng còn nhớ đến Apple bởi slogan “Think different” và những sáng tạo không ngừng trên những sản phẩm đã ra mắt. Năm 2007, chiếc iPhone đầu tiên ra đời đánh dấu bước tiến lớn trong ngành công nghiệp smartphone. Cũng kể từ đó, iPhone luôn được nhớ đến với những thiết kế thời thượng, tính năng khác biệt, dẫn đầu xu hướng và vượt lên trên tất cả các nhà sản xuất khác trong ngành.",
                            IsRemove = false,
                            Name = "Apple",
                            UrlHandle = "apple"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Samsung là tập đoàn đa quốc gia thành lập từ năm 1938 và có trụ sở tại Seoul, Hàn Quốc. Ra đời và hoạt động từ quốc gia có ngành công nghiệp hiện đại, phát triển, Samsung nhanh chóng đạt được các cột mốc ấn tượng. Không chỉ dừng lại ở một dòng sản phẩm, Samsung không ngừng sáng tạo, thử nghiệm công nghệ mới, liên tục giới thiệu rất nhiều thiết bị điện tử hữu ích cho cuộc sống hàng ngày. Nhưng trong đó, các mẫu smartphone vẫn là dòng sản phẩm chủ lực, được công ty đầu tư phát triển, đổi mới không ngừng. Tại Việt Nam, một số mẫu điện thoại Samsung phổ biến như Galaxy A, Galaxy S, Galaxy Z,...",
                            IsRemove = false,
                            Name = "Samsung",
                            UrlHandle = "samsung"
                        },
                        new
                        {
                            Id = 3,
                            Description = "OPPO là một thương hiệu smartphone đến từ Trung Quốc. Tại quê nhà, OPPO đối đầu trực tiếp với Huawei và xuất sắc vượt lên với 16.8% thị phần. Trở thành thương hiệu di động bán chạy nhất Trung Quốc, đó vừa là niềm tự hào, vừa là trách nhiệm của hãng để luôn đáp ứng kỳ vọng của người dùng. Tại thị trường Việt Nam, OPPO mới vào cuộc chưa lâu nhưng đã chiếm số thị phần rất ấn tượng. Cụ thể là từ 7% vào năm 2014, đến tháng 9/2016, con số này đã là 27.2%. Thậm chí, từ một kẻ ngáng đường, OPPO ngang nhiên chiếm vị trí của Nokia và trở thành thương hiệu smartphone thứ hai tại Việt Nam, chỉ xếp sau Samsung. Thành công của OPPO đến từ nhiều yếu tố. Đầu tiên phải kể đến là cách truyền thông rất khôn ngoan khi luôn gắn sản phẩm với gương mặt người nổi tiếng. Nhắc đến OPPO là nhớ ngay đến Sơn Tùng MTP, đến Noo Phước Thịnh, Hồ Ngọc Hà,… Chiếc di động OPPO xuất hiện dày đặc trên banner đường phố, trên truyền hình, hay thậm chí là đi vào lời hát. Nhiêu đó là đủ để công chúng có một cảm nhận dù chưa rõ ràng về tính cách chiếc điện thoại OPPO. Đó là một sản phẩm bóng bẩy, thời thượng, hào hoa, luôn luôn mới mẻ và gây chú ý.",
                            IsRemove = false,
                            Name = "OPPO",
                            UrlHandle = "oppo"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Nokia – thương hiệu điện thoại đến từ Phần Lan, là một trong những thương hiệu đi đầu lịch sử ngành công nghiệp sản xuất điện thoại di động. Từ những chiếc điện thoại không dây “cục gạch” đầu tiên, Nokia đã trở thành “ông vua” vào những năm 90 của thế kỉ 20 và đầu thế kỉ 21. Vào thời kỳ hoàng kim của mình, sản phẩm của Nokia chiếm lĩnh 41% thị trường điện thoại di động. Đó là điều mà không một hãng điện thoại di động nào khác cho đến thời điểm hiện tại, kể cả “gã khổng lồ” Samsung hay Apple có thể làm được. Tuy nhiên, với những bước đi không mấy “sáng suốt”, “ông vua” đã dần bị quên lãng và chính thức đánh rơi vị trí nhà sản xuất điện thoại số 1 thế giới vào tay hãng điện thoại Samsung của Hàn Quốc vào năm 2012. Sau một thời gian ngưng sản xuất, từ năm 2017, thương hiệu điện thoại “vang bóng một thời” đã quay trở lại với sự kết hợp của bộ ba công ty: Nokia Technologies, HMD và Foxconn. Lần này trở lại, Nokia mang khát vọng lấy lại ánh hào quang. Những sản phẩm đánh dấu sự trở lại của Nokia là điện thoại feature phone một thời làm nên tên tuổi của hãng và cả những chiếc smartphone tuyệt nhiên sẽ không làm người dùng thất vọng.'",
                            IsRemove = false,
                            Name = "Nokia",
                            UrlHandle = "nokia"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Vivo là hãng điện thoại đến từ Trung Quốc, với lợi thế về điện thoại có cấu hình mạnh mẽ và giá thảnh rẻ phù hợp với thị trường Việt Nam. Được thành lập năm 2009 tuy nhiên mãi tới 2011 Vivo mới cho ra mắt sản phẩm đầu tiên của mình, lý do là trong thời gian đó nhà sản xuất điện thoại giá rẻ này tập trung vào mảng màn hình độ phân giải và âm thanh chất lượng cho smartphone. Khi vào Việt Nam, Vivo khá thông minh khi lựa chọn chiến lược tiếp cận những khách hàng tầm trung trở xuống với chiến lược giá thấp cùng cấu hình tạm ổn, màn hình lớn. Với chiến lược này Vivo tạm thời đã có một chỗ đứng trong thị trường điện thoại smartphone giá rẻ đang rất nhiều đối thủ cạnh tranh.",
                            IsRemove = false,
                            Name = "Vivo",
                            UrlHandle = "vivo"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Thương hiệu Xiaomi ra đời từ năm 2010 với trụ sở đặt tại Bắc Kinh, Trung Quốc. Tính đến thời điểm hiện tại, thương hiệu đã hoạt động trên thị trường hơn 13 năm và đạt được nhiều kỷ lục trong ngành. “Ông lớn” Trung Quốc cũng là một trong năm nhà sản xuất smartphone lớn nhất thế giới. Các mẫu điện thoại của hãng xuất hiện ở tất cả các phân khúc, từ giá rẻ, tầm trung đến những flagship cao cấp. Khi thị trường công nghệ phát triển và thay đổi không ngừng mang đến cơ hội cho Xiaomi mở rộng danh mục sản phẩm của mình. Người dùng có thể dễ dàng tìm mua được các mẫu loa, sạc dự phòng, gia dụng,... của thương hiệu này với mức giá vô cùng hợp lý.",
                            IsRemove = false,
                            Name = "Xiaomi",
                            UrlHandle = "xiaomi"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Realme là một thương hiệu điện thoại giá rẻ dành cho phân khúc bình dân. Realme do OPPO hợp tác với Amazon tạo dựng nên với mục đích cạnh tranh trực tiếp với Xiaomi – một hãng điện thoại giá rẻ khác đến từ Trung Quốc. Nguồn gốc của hãng Realme là dòng sản phẩm OPPO Real. Realme chính thức tách khỏi OPPO vào ngày 4/5/2018 và do Sky Li lãnh đạo. Ban đầu, hãng chỉ có mặt tại Ấn Độ, một thị trường đông dân và khá sôi động. Sau đó, chiến lược kinh doanh của Realme thay đổi và được mở rộng đến nhiều thị trường khu vực Đông Á và Đông Nam Á hơn, trong đó có Việt Nam. Realme chính thức đặt chân đến Việt Nam vào tháng 10/2018 với sự góp mặt của bộ đôi Realme 2 và Realme 2 Pro (bao gồm nhiều phiên bản bộ nhớ) cùng chiếc Realme C1. Các sản phẩm của hãng được đánh giá khá tốt về thiết kế bên ngoài, các tính năng và đặc biệt là mức giá vô cùng hấp dẫn. Các chiến lược truyền thông của hãng di động Trung Quốc này cũng khá rõ ràng và hiệu quả, nhắm tới đối tượng người dùng phổ thông. Trong thời gian tới, Realme tiếp tục phát triển và sẽ tung ra nhiều sản phẩm đáng chú ý hơn nữa để đáp ứng nhu cầu của người dùng.",
                            IsRemove = false,
                            Name = "Realme",
                            UrlHandle = "realme"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.BrandCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("BrandId")
                        .HasColumnType("int");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("CategoryId");

                    b.ToTable("BrandCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            CategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 1,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 1,
                            CategoryId = 6
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 1,
                            CategoryId = 9
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 2,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 2,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 8,
                            BrandId = 2,
                            CategoryId = 4
                        },
                        new
                        {
                            Id = 9,
                            BrandId = 2,
                            CategoryId = 6
                        },
                        new
                        {
                            Id = 10,
                            BrandId = 2,
                            CategoryId = 9
                        },
                        new
                        {
                            Id = 11,
                            BrandId = 3,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 12,
                            BrandId = 3,
                            CategoryId = 3
                        },
                        new
                        {
                            Id = 13,
                            BrandId = 3,
                            CategoryId = 6
                        },
                        new
                        {
                            Id = 14,
                            BrandId = 3,
                            CategoryId = 9
                        },
                        new
                        {
                            Id = 15,
                            BrandId = 4,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 16,
                            BrandId = 5,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 17,
                            BrandId = 6,
                            CategoryId = 1
                        },
                        new
                        {
                            Id = 18,
                            BrandId = 7,
                            CategoryId = 1
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UrlHandle")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ĐIỆN THOẠI",
                            UrlHandle = "dien-thoai"
                        },
                        new
                        {
                            Id = 2,
                            Name = "LAPTOP",
                            UrlHandle = "laptop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "ĐỒNG HỒ",
                            UrlHandle = "dong-ho"
                        },
                        new
                        {
                            Id = 4,
                            Name = "SMART TV",
                            UrlHandle = "smart-tv"
                        },
                        new
                        {
                            Id = 5,
                            Name = "SMART HOME",
                            UrlHandle = "smart-home"
                        },
                        new
                        {
                            Id = 6,
                            Name = "TABLET",
                            UrlHandle = "tablet"
                        },
                        new
                        {
                            Id = 7,
                            Name = "PHỤ KIỆN",
                            UrlHandle = "phu-kien"
                        },
                        new
                        {
                            Id = 8,
                            Name = "THẺ SIM",
                            UrlHandle = "the-sim"
                        },
                        new
                        {
                            Id = 9,
                            Name = "ÂM THANH",
                            UrlHandle = "am-thanh"
                        },
                        new
                        {
                            Id = 10,
                            Name = "ĐỒ CHƠI CN",
                            UrlHandle = "do-choi-cn"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img = "44444.webp",
                            Name = "Black",
                            Price = 0L,
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46"
                        },
                        new
                        {
                            Id = 2,
                            Img = "33333.webp",
                            Name = "Silver",
                            Price = 300000L,
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46"
                        },
                        new
                        {
                            Id = 3,
                            Img = "222222.webp",
                            Name = "Gold",
                            Price = 300000L,
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46"
                        },
                        new
                        {
                            Id = 4,
                            Img = "1111.webp",
                            Name = "Deep Purple",
                            Price = 300000L,
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46"
                        },
                        new
                        {
                            Id = 5,
                            Img = "44444.webp",
                            Name = "Black",
                            Price = 0L,
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8"
                        },
                        new
                        {
                            Id = 6,
                            Img = "33333.webp",
                            Name = "Silver",
                            Price = 300000L,
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8"
                        },
                        new
                        {
                            Id = 7,
                            Img = "222222.webp",
                            Name = "Gold",
                            Price = 300000L,
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8"
                        },
                        new
                        {
                            Id = 8,
                            Img = "1111.webp",
                            Name = "Deep Purple",
                            Price = 300000L,
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8"
                        },
                        new
                        {
                            Id = 9,
                            Img = "anh-chup-man-hinh-2022-09-08-luc-01-59-53-removebg-preview.webp",
                            Name = "Red",
                            Price = 0L,
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2"
                        },
                        new
                        {
                            Id = 10,
                            Img = "anh-chup-man-hinh-2022-09-08-luc-01-57-13-removebg-preview.webp",
                            Name = "Blue",
                            Price = 300000L,
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2"
                        },
                        new
                        {
                            Id = 11,
                            Img = "14-yellow.webp",
                            Name = "Yellow",
                            Price = 300000L,
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2"
                        },
                        new
                        {
                            Id = 12,
                            Img = "2222.webp",
                            Name = "Purple",
                            Price = 300000L,
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2"
                        },
                        new
                        {
                            Id = 13,
                            Img = "anh-chup-man-hinh-2022-09-08-luc-01-59-18-removebg-preview.webp",
                            Name = "Starlight",
                            Price = 300000L,
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2"
                        },
                        new
                        {
                            Id = 14,
                            Img = "anh-chup-man-hinh-2022-09-08-luc-01-58-38-removebg-preview.webp",
                            Name = "Midnight",
                            Price = 300000L,
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2"
                        },
                        new
                        {
                            Id = 15,
                            Img = "a33-1.webp",
                            Name = "Đen",
                            Price = 0L,
                            ProductId = "0ed9c3f3-3eac-4717-83ae-7cb866cfaec9"
                        },
                        new
                        {
                            Id = 16,
                            Img = "a33-2.webp",
                            Name = "Trắng",
                            Price = 0L,
                            ProductId = "0ed9c3f3-3eac-4717-83ae-7cb866cfaec9"
                        },
                        new
                        {
                            Id = 17,
                            Img = "image-removebg-preview-27.webp",
                            Name = "Đen",
                            Price = 0L,
                            ProductId = "3e8d0cb5-4cf7-4ca9-8c76-88b78fde774a"
                        },
                        new
                        {
                            Id = 18,
                            Img = "image-removebg-preview-2.webp",
                            Name = "Bạc",
                            Price = 0L,
                            ProductId = "3e8d0cb5-4cf7-4ca9-8c76-88b78fde774a"
                        },
                        new
                        {
                            Id = 19,
                            Img = "image-removebg-preview-28.webp",
                            Name = "Xanh",
                            Price = 0L,
                            ProductId = "3e8d0cb5-4cf7-4ca9-8c76-88b78fde774a"
                        },
                        new
                        {
                            Id = 20,
                            Img = "image-removebg-preview-26_638018739441185433.webp",
                            Name = "Đen",
                            Price = 0L,
                            ProductId = "e6cd1bce-c1ef-4ccb-a1d0-a122372b3423"
                        },
                        new
                        {
                            Id = 21,
                            Img = "image-removebg-preview-25_638018739643684615.webp",
                            Name = "Xanh",
                            Price = 0L,
                            ProductId = "e6cd1bce-c1ef-4ccb-a1d0-a122372b3423"
                        },
                        new
                        {
                            Id = 22,
                            Img = "oppo-a16-3g32g-3.webp",
                            Name = "Đen",
                            Price = 0L,
                            ProductId = "3c183845-7b58-43bc-8253-036a5ecabff1"
                        },
                        new
                        {
                            Id = 23,
                            Img = "oppo-a16-3g32g-1.webp",
                            Name = "Bạc",
                            Price = 0L,
                            ProductId = "3c183845-7b58-43bc-8253-036a5ecabff1"
                        },
                        new
                        {
                            Id = 24,
                            Img = "image-removebg-preview-5.webp",
                            Name = "Vàng phù sa",
                            Price = 0L,
                            ProductId = "4d0c8c2d-65a3-47c0-a9e3-8d03eb96f3ca"
                        },
                        new
                        {
                            Id = 25,
                            Img = "xanh.webp",
                            Name = "Xanh thiên thạch",
                            Price = 0L,
                            ProductId = "4d0c8c2d-65a3-47c0-a9e3-8d03eb96f3ca"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ColorId")
                        .HasColumnType("int");

                    b.Property<int?>("MemoryAndStorageId")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("MemoryAndStorageId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("Details");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 1,
                            MemoryAndStorageId = 1,
                            OrderId = "e7814579-4f5a-47c4-bfec-84a8f2ba7757",
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 5,
                            MemoryAndStorageId = 5,
                            OrderId = "e7814579-4f5a-47c4-bfec-84a8f2ba7757",
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8",
                            Quantity = 2
                        },
                        new
                        {
                            Id = 3,
                            ColorId = 5,
                            MemoryAndStorageId = 5,
                            OrderId = "e7814579-4f5a-47c4-bfec-84a8f2ba7757",
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8",
                            Quantity = 1
                        },
                        new
                        {
                            Id = 4,
                            ColorId = 9,
                            MemoryAndStorageId = 9,
                            OrderId = "e7814579-4f5a-47c4-bfec-84a8f2ba7757",
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2",
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.FrontCamera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Feature")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("[ProductId] IS NOT NULL");

                    b.ToTable("FrontCameras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Feature = "Xóa phông,Quay video 4K,Retina Flash,Quay video Full HD,Tự động lấy nét (AF),Smart HDR 4,Bộ lọc màu,Live Photo,Trôi nhanh thời gian (Time Lapse),Chụp đêm,Quay chậm (Slow Motion),Cinematic",
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46",
                            Resolution = "12 MP"
                        },
                        new
                        {
                            Id = 2,
                            Feature = "Tự động lấy nét với Focus Pixels,Thấu kính sáu phần tử,Retina Flash,Photogenic Engine,Deep Fusion,HDR thông minh,Chế độ chân dung với hiệu ứng bokeh nâng cao và Kiểm soát độ sâu,Portrait Lighting với sáu hiệu ứng (Tự nhiên, Studio, Đường viền, Sân khấu, Sân khấu Mono, High Key Mono),Animoji và Memoji,Chế độ ban đêm",
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8",
                            Resolution = "12 MP"
                        },
                        new
                        {
                            Id = 3,
                            Feature = "Quay video 4K tối đa 60 fps,Chế độ điện ảnh lên đến 4K HDR ở tốc độ 30 fps,Quay video HDR với Dolby Vision lên đến 4K ở tốc độ 60 fps,Hỗ trợ video chuyển động cho 1080p ở tốc độ 120 fps,Video tua nhanh thời gian với tính năng ổn định,Chế độ ban đêm Thời gian trôi đi,Video QuickTake,Ổn định video điện ảnh (4K, 1080p và 720p)",
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2",
                            Resolution = "12 MP"
                        },
                        new
                        {
                            Id = 4,
                            Feature = "Bộ lọc màu,Chụp đêm,Flash màn hình,Góc rộng (Wide),HDR,Live Photo,Làm đẹp,Nhận diện khuôn mặt,Quay video 4K,Quay video Full HD,Trôi nhanh thời gian (Time Lapse),Xóa phông",
                            ProductId = "0ed9c3f3-3eac-4717-83ae-7cb866cfaec9",
                            Resolution = "13 MP"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = "3e8d0cb5-4cf7-4ca9-8c76-88b78fde774a",
                            Resolution = "8.0 MP"
                        },
                        new
                        {
                            Id = 6,
                            Feature = "Xóa phông,Nhãn dán (AR Stickers),Toàn cảnh (Panorama),Quay video HD,Làm đẹp,Quay video Full HD,HDR,Bộ lọc màu,Trôi nhanh thời gian (Time Lapse)",
                            ProductId = "e6cd1bce-c1ef-4ccb-a1d0-a122372b3423",
                            Resolution = "5 MP"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = "3c183845-7b58-43bc-8253-036a5ecabff1",
                            Resolution = "8 MP"
                        },
                        new
                        {
                            Id = 8,
                            Feature = "Quay video HD",
                            ProductId = "4d0c8c2d-65a3-47c0-a9e3-8d03eb96f3ca",
                            Resolution = "5 MP"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.MemoryAndStorage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HardDrive")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HardDriveType")
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Price")
                        .HasColumnType("bigint");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Ram")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Rom")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("MemoryAndStorages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 0L,
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46",
                            Ram = "6GB",
                            Rom = "128GB"
                        },
                        new
                        {
                            Id = 2,
                            Price = 200000L,
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46",
                            Ram = "6GB",
                            Rom = "256GB"
                        },
                        new
                        {
                            Id = 3,
                            Price = 1000000L,
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46",
                            Ram = "6GB",
                            Rom = "512GB"
                        },
                        new
                        {
                            Id = 4,
                            Price = 2000000L,
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46",
                            Ram = "6GB",
                            Rom = "1TB"
                        },
                        new
                        {
                            Id = 5,
                            Price = 0L,
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8",
                            Ram = "6GB",
                            Rom = "128GB"
                        },
                        new
                        {
                            Id = 6,
                            Price = 200000L,
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8",
                            Ram = "6GB",
                            Rom = "256GB"
                        },
                        new
                        {
                            Id = 7,
                            Price = 1000000L,
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8",
                            Ram = "6GB",
                            Rom = "512GB"
                        },
                        new
                        {
                            Id = 8,
                            Price = 2000000L,
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8",
                            Ram = "6GB",
                            Rom = "1TB"
                        },
                        new
                        {
                            Id = 9,
                            Price = 0L,
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2",
                            Ram = "6GB",
                            Rom = "128GB"
                        },
                        new
                        {
                            Id = 10,
                            Price = 200000L,
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2",
                            Ram = "6GB",
                            Rom = "256GB"
                        },
                        new
                        {
                            Id = 11,
                            Price = 1000000L,
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2",
                            Ram = "6GB",
                            Rom = "512GB"
                        },
                        new
                        {
                            Id = 12,
                            Price = 0L,
                            ProductId = "0ed9c3f3-3eac-4717-83ae-7cb866cfaec9",
                            Ram = "6GB",
                            Rom = "128GB"
                        },
                        new
                        {
                            Id = 13,
                            Price = 0L,
                            ProductId = "3e8d0cb5-4cf7-4ca9-8c76-88b78fde774a",
                            Ram = "4GB",
                            Rom = "128GB"
                        },
                        new
                        {
                            Id = 14,
                            Price = 0L,
                            ProductId = "e6cd1bce-c1ef-4ccb-a1d0-a122372b3423",
                            Ram = "4GB",
                            Rom = "64GB"
                        },
                        new
                        {
                            Id = 15,
                            Price = 0L,
                            ProductId = "3c183845-7b58-43bc-8253-036a5ecabff1",
                            Ram = "3GB",
                            Rom = "32GB"
                        },
                        new
                        {
                            Id = 16,
                            Price = 0L,
                            ProductId = "4d0c8c2d-65a3-47c0-a9e3-8d03eb96f3ca",
                            Ram = "2GB",
                            Rom = "32GB"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.OSAndCPU", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpu")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CpuSpeed")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Gpu")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("[ProductId] IS NOT NULL");

                    b.ToTable("OSAndCPUs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cpu = "Apple A16 Bionic 6 nhân",
                            CpuSpeed = "3.46 GHz",
                            Gpu = "Apple GPU 5 nhân",
                            OperatingSystem = "iOS 16",
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46"
                        },
                        new
                        {
                            Id = 2,
                            Cpu = "A16 Bionic",
                            CpuSpeed = "3.46 GHz",
                            Gpu = "Apple GPU",
                            OperatingSystem = "iOS 16",
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8"
                        },
                        new
                        {
                            Id = 3,
                            Cpu = "A15 Bionic",
                            OperatingSystem = "iOS 16",
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2"
                        },
                        new
                        {
                            Id = 4,
                            Cpu = "Exynos 1280 8 nhân",
                            CpuSpeed = "2 nhân 2.4 GHz & 6 nhân 2 GHz",
                            OperatingSystem = "Android 12",
                            ProductId = "0ed9c3f3-3eac-4717-83ae-7cb866cfaec9"
                        },
                        new
                        {
                            Id = 5,
                            Cpu = "SnapDragon 695 5G",
                            OperatingSystem = "Android 12",
                            ProductId = "3e8d0cb5-4cf7-4ca9-8c76-88b78fde774a"
                        },
                        new
                        {
                            Id = 6,
                            Cpu = "MediaTek Helio G35 8 nhân",
                            CpuSpeed = "2.3 GHz",
                            Gpu = "IMG PowerVR GE8320",
                            OperatingSystem = "Android 12",
                            ProductId = "e6cd1bce-c1ef-4ccb-a1d0-a122372b3423"
                        },
                        new
                        {
                            Id = 7,
                            Cpu = "Helio G35, tối đa 2.3GHz",
                            Gpu = "IMG GE8320@680MHz",
                            OperatingSystem = "ColorOS 11.1, nền tảng Android 11",
                            ProductId = "3c183845-7b58-43bc-8253-036a5ecabff1"
                        },
                        new
                        {
                            Id = 8,
                            CpuSpeed = "4 nhân 1.6 GHz & 4 nhân 1.2 GHz",
                            Gpu = "Mali-G52 MC2",
                            OperatingSystem = "Android 11 (Go Edition)",
                            ProductId = "4d0c8c2d-65a3-47c0-a9e3-8d03eb96f3ca"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.Order", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CustomerNotes")
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StoreNotes")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = "e7814579-4f5a-47c4-bfec-84a8f2ba7757",
                            Address = "số 1, đường số 2",
                            Date = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nguyễn Văn A",
                            PhoneNumber = "0909000021",
                            Status = "Chờ xác nhận"
                        },
                        new
                        {
                            Id = "c5aeacc4-6208-463d-8d7b-0c4125a32c65",
                            Address = "số 1, đường số 2",
                            Date = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nguyễn Văn A",
                            PhoneNumber = "0909000021",
                            Status = "Đã giao"
                        },
                        new
                        {
                            Id = "2b5f5cbc-7e11-4f6a-91f2-bae6ffb65f63",
                            Address = "số 1, đường số 2",
                            Date = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Nguyễn Văn A",
                            PhoneNumber = "0909000021",
                            Status = "Đã xác nhận"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.Product", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("BrandCategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(1500)");

                    b.Property<long>("ImportPrice")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsRemove")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("SellingPrice")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BrandCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "2eda1bf0-211d-4772-8d6c-f01460438a46",
                            BrandCategoryId = 1,
                            Date = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 100000L,
                            IsRemove = false,
                            Name = "iPhone 14 Pro Max",
                            SellingPrice = 26290000L
                        },
                        new
                        {
                            Id = "8272f141-90dd-4149-a645-a42c62e4c3a8",
                            BrandCategoryId = 1,
                            Date = new DateTime(2023, 5, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 100000L,
                            IsRemove = false,
                            Name = "iPhone 14 Pro",
                            SellingPrice = 24690000L
                        },
                        new
                        {
                            Id = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2",
                            BrandCategoryId = 1,
                            Date = new DateTime(2023, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 100000L,
                            IsRemove = false,
                            Name = "iPhone 14",
                            SellingPrice = 18990000L
                        },
                        new
                        {
                            Id = "0ed9c3f3-3eac-4717-83ae-7cb866cfaec9",
                            BrandCategoryId = 6,
                            Date = new DateTime(2023, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 100000L,
                            IsRemove = false,
                            Name = "Samsung Galaxy A33",
                            SellingPrice = 6350000L
                        },
                        new
                        {
                            Id = "3e8d0cb5-4cf7-4ca9-8c76-88b78fde774a",
                            BrandCategoryId = 6,
                            Date = new DateTime(2023, 5, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 100000L,
                            IsRemove = false,
                            Name = "Samsung Galaxy A23",
                            SellingPrice = 5240000L
                        },
                        new
                        {
                            Id = "e6cd1bce-c1ef-4ccb-a1d0-a122372b3423",
                            BrandCategoryId = 11,
                            Date = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 100000L,
                            IsRemove = false,
                            Name = "Oppo A17",
                            SellingPrice = 3990000L
                        },
                        new
                        {
                            Id = "3c183845-7b58-43bc-8253-036a5ecabff1",
                            BrandCategoryId = 11,
                            Date = new DateTime(2023, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 100000L,
                            IsRemove = false,
                            Name = "Oppo A16",
                            SellingPrice = 2790000L
                        },
                        new
                        {
                            Id = "4d0c8c2d-65a3-47c0-a9e3-8d03eb96f3ca",
                            BrandCategoryId = 15,
                            Date = new DateTime(2023, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ImportPrice = 100000L,
                            IsRemove = false,
                            Name = "Nokia C20",
                            SellingPrice = 1480000L
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.RearCamera", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Feature")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Film")
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FlashLight")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("[ProductId] IS NOT NULL");

                    b.ToTable("RearCameras");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Feature = "Ban đêm (Night Mode),Trôi nhanh thời gian (Time Lapse),Quay chậm (Slow Motion),Xóa phông,Zoom quang học,Toàn cảnh (Panorama),Chống rung quang học (OIS),Smart HDR 4,Live Photo,Bộ lọc màu,Cinematic,Dolby Vision HDR,Zoom kỹ thuật số,Siêu cận (Macro),Góc siêu rộng (Ultrawide),Chế độ hành động (Action Mode),Deep Fusion",
                            Film = "HD 720p@30fps,FullHD 1080p@60fps,FullHD 1080p@30fps,4K 2160p@24fps,4K 2160p@30fps,4K 2160p@60fps",
                            FlashLight = "Có",
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46",
                            Resolution = "Chính 48 MP & Phụ 12 MP, 12 MP"
                        },
                        new
                        {
                            Id = 2,
                            Feature = "Nắp ống kính tinh thể sapphirePhotogenic Engine,Deep Fusion,HDR thông minh,Chế độ chân dung với hiệu ứng bokeh nâng cao và Kiểm soát độ sâu,Portrait Lighting với sáu hiệu ứng (Tự nhiên, Studio, Đường viền, Sân khấu, Sân khấu Mono, High Key Mono),Chế độ ban đêm,Chụp chân dung ở chế độ ban đêm được bật bởi LiDAR Scanner,Toàn cảnh (lên đến 63MP),Chụp ảnh phong cách",
                            Film = "Quay video 4K ở tốc độ 60 fps,Quay video HD 1080p ở tốc độ 60 fps,Quay video HD 720p ở tốc độ 30 fps,Chế độ điện ảnh lên đến 4K HDR ở tốc độ 30 fps,Chế độ hành động lên đến 2,8K ở tốc độ 60 fps,Quay video HDR với Dolby Vision lên đến 4K ở tốc độ 60 fps",
                            FlashLight = "True Tone thích ứng",
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8",
                            Resolution = "48MP x 12MP x 12MP"
                        },
                        new
                        {
                            Id = 3,
                            Feature = "Nắp ống kính tinh thể sapphire,Photogenic Engine,Deep Fusion,HDR thông minh 4,Chế độ chân dung với hiệu ứng bokeh nâng cao và Kiểm soát độ sâu,Portrait Lighting với sáu hiệu ứng (Tự nhiên, Studio, Đường viền, Sân khấu, Sân khấu Mono, High Key Mono),Chế độ ban đêm,Toàn cảnh (lên đến 63MP),Chụp ảnh phong cách,Chụp màu rộng cho ảnh và Ảnh trực tiếp,Hiệu chỉnh ống kính (Siêu rộng),Chỉnh sửa mắt đỏ nâng cao,Ổn định hình ảnh tự động,Chế độ chụp,Gắn thẻ địa lý cho ảnh",
                            Film = "Quay video 4K tối đa 60 fps,Quay video HD 1080p tối đa 60 fps,Quay video HD 720p tối đa 30 fps,Chế độ điện ảnh lên đến 4K HDR ở tốc độ 30 fps,Chế độ hành động lên đến 2,8K ở tốc độ 60 fps,Quay video HDR với Dolby Vision lên đến 4K ở tốc độ 60 fps,Hỗ trợ video chuyển động chậm cho 1080p tối đa 240 fps,Video tua nhanh thời gian với tính năng ổn định,Chế độ ban đêm,Time-lapse",
                            FlashLight = "True Tone",
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2",
                            Resolution = "12MP x 12MP"
                        },
                        new
                        {
                            Id = 4,
                            Feature = "Bộ lọc màu,Chuyên nghiệp (Pro),Chạm lấy nét,Chống rung quang học (OIS),Góc rộng (Wide),Góc siêu rộng (Ultrawide),HDR,Làm đẹp,Lấy nét theo pha (PDAF),Nhận diện khuôn mặt,Quay chậm (Slow Motion),Quay Siêu chậm (Super Slow Motion),Siêu cận (Macro),Toàn cảnh (Panorama),Trôi nhanh thời gian (Time Lapse),Tự động lấy nét (AF),Xóa phông,Zoom kỹ thuật số",
                            Film = "4K 2160p@30fps,FullHD 1080p@30fps,FullHD 1080p@60fps,HD 720p@30fps",
                            FlashLight = "Night Mode",
                            ProductId = "0ed9c3f3-3eac-4717-83ae-7cb866cfaec9",
                            Resolution = "Chính 48 MP & Phụ 8 MP, 5 MP, 2 MP"
                        },
                        new
                        {
                            Id = 5,
                            Feature = "Chống rung OIS 2022,Chụp ảnh chân dung,Chụp Cận Cảnh",
                            Film = "FHD (1920 x 1080)@30fps",
                            FlashLight = "Có",
                            ProductId = "3e8d0cb5-4cf7-4ca9-8c76-88b78fde774a",
                            Resolution = "50.0 MP x 5.0 MP x 2.0 MP x 2.0 MP"
                        },
                        new
                        {
                            Id = 6,
                            Feature = "AI Camera,Ban đêm (Night Mode),Trôi nhanh thời gian (Time Lapse),Chụp bằng cử chỉ,Toàn cảnh (Panorama),HDR,Chuyên nghiệp (Pro),Bộ lọc màu,Nhãn dán (AR Stickers),Làm đẹp,Google Lens,Zoom kỹ thuật số",
                            Film = "HD 720p@30fps,FullHD 1080p@30fps",
                            FlashLight = "Có",
                            ProductId = "e6cd1bce-c1ef-4ccb-a1d0-a122372b3423",
                            Resolution = "Chính 50 MP & Phụ 0.3 M"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = "3c183845-7b58-43bc-8253-036a5ecabff1",
                            Resolution = "13 MP (chính) + 2 MP (mono) + 2 MP (marco)"
                        },
                        new
                        {
                            Id = 8,
                            Feature = "HDR",
                            Film = "HD 720p@30fps",
                            ProductId = "4d0c8c2d-65a3-47c0-a9e3-8d03eb96f3ca",
                            Resolution = "5 MP"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "8b3fc0d4-19f3-4063-b9ab-26d513c03b2c",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "06f891c8-0876-4065-8f18-e018180d0c01",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.Screen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MaximumBrightness")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProductId")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Resolution")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ScreenTechnology")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TouchScreen")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Widescreen")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique()
                        .HasFilter("[ProductId] IS NOT NULL");

                    b.ToTable("Screens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MaximumBrightness = "2000 nits",
                            ProductId = "2eda1bf0-211d-4772-8d6c-f01460438a46",
                            Resolution = "2796 x 1290 Pixels",
                            ScreenTechnology = "OLED",
                            TouchScreen = "Kính cường lực Ceramic Shield",
                            Widescreen = "6.7\""
                        },
                        new
                        {
                            Id = 2,
                            MaximumBrightness = "2000 nits",
                            ProductId = "8272f141-90dd-4149-a645-a42c62e4c3a8",
                            Resolution = "Super Retina XDR (2556 x 1179-pixel)",
                            ScreenTechnology = "OLED",
                            TouchScreen = "Ceramic Shield",
                            Widescreen = "6.1‑inch"
                        },
                        new
                        {
                            Id = 3,
                            MaximumBrightness = "1200 nits",
                            ProductId = "3dc3fcd4-ea20-4dad-bf4d-ebc0ccb815a2",
                            Resolution = "2532 x 1170",
                            ScreenTechnology = "Super Retina XDR",
                            TouchScreen = "Ceramic Shield",
                            Widescreen = "OLED 6.1‑inch"
                        },
                        new
                        {
                            Id = 4,
                            MaximumBrightness = "800 nits",
                            ProductId = "0ed9c3f3-3eac-4717-83ae-7cb866cfaec9",
                            Resolution = "Full HD+ (1080 x 2400 Pixels)",
                            ScreenTechnology = "Super AMOLED",
                            Widescreen = "6.4\" - Tần số quét 90 Hz"
                        },
                        new
                        {
                            Id = 5,
                            ProductId = "3e8d0cb5-4cf7-4ca9-8c76-88b78fde774a",
                            Resolution = "1080 x 2408 pixels",
                            ScreenTechnology = "PLS LCD",
                            TouchScreen = "Kính cường lực Corning Gorilla Glass 5",
                            Widescreen = "6.6\" - tần số quét 120Hz"
                        },
                        new
                        {
                            Id = 6,
                            MaximumBrightness = "600 nits",
                            ProductId = "e6cd1bce-c1ef-4ccb-a1d0-a122372b3423",
                            Resolution = "HD+ (720 x 1612 Pixels)",
                            ScreenTechnology = "PLS LCD",
                            TouchScreen = "Kính cường lực Panda"
                        },
                        new
                        {
                            Id = 7,
                            ProductId = "3c183845-7b58-43bc-8253-036a5ecabff1",
                            Resolution = "720 x 1600 (HD+)",
                            ScreenTechnology = "LCD",
                            TouchScreen = "Kính cường lực Panda",
                            Widescreen = "6.52 inch, màn hình giọt nước"
                        },
                        new
                        {
                            Id = 8,
                            ProductId = "4d0c8c2d-65a3-47c0-a9e3-8d03eb96f3ca",
                            Resolution = "HD+ (720 x 1600 Pixels)",
                            ScreenTechnology = "IPS LCD"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.Slide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Img")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Slides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Img = "banner-xa-kho-laptop-01.png"
                        },
                        new
                        {
                            Id = 2,
                            Img = "oppo-a77s-01_638192222109753594.jpg"
                        },
                        new
                        {
                            Id = 3,
                            Img = "redmi-note-12-series-pc.png"
                        },
                        new
                        {
                            Id = 4,
                            Img = "taba8-web-1.jpg"
                        },
                        new
                        {
                            Id = 5,
                            Img = "web-galaxy-z-fold4-z-flip4-03.jpg"
                        },
                        new
                        {
                            Id = 6,
                            Img = "yuho-tab-8-01.jpg"
                        });
                });

            modelBuilder.Entity("CongNgheStore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(12)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("CongNgheStore.Models.BatteryAndCharger", b =>
                {
                    b.HasOne("CongNgheStore.Models.Product", "Product")
                        .WithOne("BatteryAndCharger")
                        .HasForeignKey("CongNgheStore.Models.BatteryAndCharger", "ProductId")
                        .HasConstraintName("FK_BatteryAndCharger_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CongNgheStore.Models.BrandCategory", b =>
                {
                    b.HasOne("CongNgheStore.Models.Brand", "Brand")
                        .WithMany("BrandCategories")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("FK_BrandCategory_Brand");

                    b.HasOne("CongNgheStore.Models.Category", "Category")
                        .WithMany("BrandCategories")
                        .HasForeignKey("CategoryId")
                        .HasConstraintName("FK_BrandCategory_Category");

                    b.Navigation("Brand");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CongNgheStore.Models.Color", b =>
                {
                    b.HasOne("CongNgheStore.Models.Product", "Product")
                        .WithMany("Colors")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_Colors_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CongNgheStore.Models.Detail", b =>
                {
                    b.HasOne("CongNgheStore.Models.Color", "Color")
                        .WithMany("Details")
                        .HasForeignKey("ColorId")
                        .HasConstraintName("FK_Details_Color");

                    b.HasOne("CongNgheStore.Models.MemoryAndStorage", "MemoryAndStorage")
                        .WithMany("Details")
                        .HasForeignKey("MemoryAndStorageId")
                        .HasConstraintName("FK_Details_MemoryAndStorage");

                    b.HasOne("CongNgheStore.Models.Order", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .HasConstraintName("FK_Details_Order");

                    b.HasOne("CongNgheStore.Models.Product", "Product")
                        .WithMany("Details")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_Details_Product");

                    b.Navigation("Color");

                    b.Navigation("MemoryAndStorage");

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CongNgheStore.Models.FrontCamera", b =>
                {
                    b.HasOne("CongNgheStore.Models.Product", "Product")
                        .WithOne("FrontCamera")
                        .HasForeignKey("CongNgheStore.Models.FrontCamera", "ProductId")
                        .HasConstraintName("FK_FrontCamera_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CongNgheStore.Models.MemoryAndStorage", b =>
                {
                    b.HasOne("CongNgheStore.Models.Product", "Product")
                        .WithMany("MemoryAndStorages")
                        .HasForeignKey("ProductId")
                        .HasConstraintName("FK_MemoryAndStorages_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CongNgheStore.Models.OSAndCPU", b =>
                {
                    b.HasOne("CongNgheStore.Models.Product", "Product")
                        .WithOne("OSAndCPU")
                        .HasForeignKey("CongNgheStore.Models.OSAndCPU", "ProductId")
                        .HasConstraintName("FK_OSAndCPU_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CongNgheStore.Models.Order", b =>
                {
                    b.HasOne("CongNgheStore.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Orders_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CongNgheStore.Models.Product", b =>
                {
                    b.HasOne("CongNgheStore.Models.BrandCategory", "BrandCategory")
                        .WithMany("Products")
                        .HasForeignKey("BrandCategoryId")
                        .HasConstraintName("FK_Products_BrandCategory");

                    b.Navigation("BrandCategory");
                });

            modelBuilder.Entity("CongNgheStore.Models.RearCamera", b =>
                {
                    b.HasOne("CongNgheStore.Models.Product", "Product")
                        .WithOne("RearCamera")
                        .HasForeignKey("CongNgheStore.Models.RearCamera", "ProductId")
                        .HasConstraintName("FK_RearCamera_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CongNgheStore.Models.Screen", b =>
                {
                    b.HasOne("CongNgheStore.Models.Product", "Product")
                        .WithOne("Screen")
                        .HasForeignKey("CongNgheStore.Models.Screen", "ProductId")
                        .HasConstraintName("FK_Screen_Product");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("CongNgheStore.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("CongNgheStore.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("CongNgheStore.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("CongNgheStore.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CongNgheStore.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("CongNgheStore.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CongNgheStore.Models.Brand", b =>
                {
                    b.Navigation("BrandCategories");
                });

            modelBuilder.Entity("CongNgheStore.Models.BrandCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("CongNgheStore.Models.Category", b =>
                {
                    b.Navigation("BrandCategories");
                });

            modelBuilder.Entity("CongNgheStore.Models.Color", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CongNgheStore.Models.MemoryAndStorage", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CongNgheStore.Models.Order", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("CongNgheStore.Models.Product", b =>
                {
                    b.Navigation("BatteryAndCharger");

                    b.Navigation("Colors");

                    b.Navigation("Details");

                    b.Navigation("FrontCamera");

                    b.Navigation("MemoryAndStorages");

                    b.Navigation("OSAndCPU");

                    b.Navigation("RearCamera");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("CongNgheStore.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
